services:
  - type: web
    name: une12-flask-cloud
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_VERSION
        value: 1.0.0
      - key: SECRET_KEY
        generateValue: true

